# Generated by Django 3.1.4 on 2021-01-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_click'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Click',
        ),
    ]
