# Generated by Django 3.1.4 on 2021-01-13 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shorten', '0002_auto_20201228_0039'),
        ('dashboard', '0004_delete_click'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateField(auto_now=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('os', models.CharField(blank=True, max_length=7, null=True)),
                ('referer', models.CharField(blank=True, max_length=200, null=True)),
                ('shorturl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorten.shorturl')),
            ],
        ),
    ]
