# Generated by Django 3.1.4 on 2021-01-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210114_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='click',
            name='click_date',
            field=models.DateField(auto_now=True),
        ),
    ]
