# Generated by Django 3.1.4 on 2021-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_shorturl_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='url_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
